name = "Firebomb"
author = "Khorne"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06cd911eabb438d8ee7bde07b15d03d09318f6d3804c18d1d983a421ae9d8d22"

[versions]
forge = "40.2.4"
minecraft = "1.18.2"
