name = "Firebomb"
author = "Khorne"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78fe676c1922808b3492661aa8b878010d804e8760f044b0c9bfdcbf34462ddc"

[versions]
forge = "40.2.2"
minecraft = "1.18.2"
