name = "Firebomb"
author = "Khorne & Hri7566"
version = "2.0.0a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "338f436f51a65fbddb06b04f589358a14dd2b25ff9b2bf12b462db5ebc6e504c"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
