name = "Firebomb"
author = "Khorne"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a53315dd2d69873d6c1b1a61ec46cb81bceacba205adbf77460d5fdb979c96f"

[versions]
forge = "40.2.2"
minecraft = "1.18.2"
