name = "Firebomb"
author = "Khorne"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "140c728442f1d6c5da4af1f26b9e6110648d0a1f18180c9a13e65c630169df61"

[versions]
forge = "40.2.2"
minecraft = "1.18.2"
