name = "Firebomb"
author = "Khorne & Hri7566"
version = "2.0.0a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37938e10a894928b33870297281d475bbd4ac9796fae64dbbeb68104d7c91730"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
