name = "Firebomb"
author = "Khorne"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0dbfc11cadcdaddd0b87eba30459d8a1f775fc19b55717a8173d594069cf4e95"

[versions]
forge = "40.2.2"
minecraft = "1.18.2"
