name = "Firebomb"
author = "Khorne"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e7965eb94460107a330eb10d61d1185c5631df71854ab0fc7bea3a1b518860a"

[versions]
forge = "40.2.2"
minecraft = "1.18.2"
